### ISSUE TITLE
DELL E5570 (ALPS v8) crashes

### ISSUE THREAD

**Issue by misa198** [SkyrilHD/VoodooPS2-ALPS#15]
Hello. I use DELL Latitude E5570 with ALPS v8.
When switching from Acidanthera's VoodooPS2 to your kext (1.0.5 & 1.0.6), my laptop often crashes. I have to be restarted with the power button. Sometimes the cursor cannot move vertically.

**Comment by SkyrilHD** [comment]
Switch to 1.0.6 DEBUG, gather logs and also send kernel panic log (with keepsyms=1) if there is one.

**Comment by misa198** [comment]
My bad. After reset NVRAM i no longer get this error. Thanks.
