### ISSUE TITLE
Random zoom-ins of web page content while scrolling with two fingers in any browser 

### ISSUE THREAD

**Issue by viking1304** [SkyrilHD/VoodooPS2-ALPS#3]
This version works much better than VoodooPS2Controller-Alps.kext, but I am experience some random zoom-ins of web page content while scrolling with two fingers in any browser (Chrome, Brave, Safari).

Unfortunately I have no idea how to find a HW version of ALPS inside my Dell E7450.

**Comment by SkyrilHD** [comment]
This is fixed in master. You can download it from here: https://github.com/SkyrilHD/VoodooPS2-ALPS/actions/runs/1427734204

**Comment by viking1304** [comment]
Thank you @SkyrilHD. It works much better with 1.4
